### ISSUE TITLE
Don't use remote example data in tests

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz-stats#114]
We are having a lot of spurious failures in both test CI jobs and RTD builds, all related to netcdf/hdf I/O or http issues.

Locally, remote datasets are not much of an issue because they get downloaded and stored in the `arviz_data` folder, so unless that folder is removed after the first time they behave like local datasets. In CI however they need to be downloaded every time CI runs and for every CI job. I suspect the multiple CI jobs trying to download the same dataset at the same time or very close to each other is triggering an issue or a figshare protection against excessive traffic.

Testing wise, I think ideally we should use mock data, with minimal data stored locally in the repo for cases where it is difficult to mock data properly. For documentation I think we can probably choose 2-3 remote datasets to use (plus the centered/non-centered ones) and if we want to use other do so in notebooks which are executed locally and only rendered when building the docs.

**Comment by OriolAbril** [comment]
For a bit more context, in https://github.com/arviz-devs/arviz-stats/pull/113 the 3.12 job failed with http error (the h5netcdf change and the .load() call in `load_arviz_data` might have fixed the hdf error) and passed after I triggered a rerun. After merging, the 3.11 CI job failed and passed after I triggered a rerun: https://github.com/arviz-devs/arviz-stats/actions/runs/14884871691

**Comment by aloctavodia** [comment]
I think the issue was caused specifically for the "anes" dataset, not entirely sure. If that's the case #135 should solve it. If not, we can remove all the remote examples. Or maybe we can remove them anyway.

**Comment by jordandeklerk** [comment]
This also randomly happens with the "radon" dataset as well, but much less often now since [#113](https://github.com/arviz-devs/arviz-stats/pull/113). I still get spurious errors here and there for it though.

**Comment by OriolAbril** [comment]
We could add more things to [`arviz_base.testing`](https://github.com/arviz-devs/arviz-base/blob/main/src/arviz_base/testing.py) to generate testing data with the shape/categories we care about but useless values in it. It will probably make tests nicer overall as we have several scattered fixtures around in the different repos that do basically this.

**Comment by aloctavodia** [comment]
This  #137 removes "radon" and adds some datasets from arviz_base. But there is still more work to do, both to potentially move more datasets to arviz_base and to tidy up the tests overall, as explained in #139
